var tree_node=new Array(0,"聚缘管理","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","","_self",-1,0,"申请表管理","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","#","_self",-1,2,"资料情况管理","","","../image/treeimg/tree_T.gif",3,"","rengzheng/apply/infromation/show.html","mainFrame",2,"费用情况管理","","","../image/treeimg/tree_T.gif",3,"","rengzheng/apply/price/show.html","mainFrame",2,"认证信息打印","","","../image/treeimg/tree_T.gif",3,"","rengzheng/apply/print/show.html","mainFrame",2,"认证信息管理","","","../image/treeimg/tree_T.gif",3,"","rengzheng/apply/show.html","mainFrame",2,"团体付款管理","","","../image/treeimg/tree_L.gif",3,"","rengzheng/apply/group/show.html","mainFrame",1,0,"反馈表管理","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","#","_self",-1,2,"反馈表管理","","","../image/treeimg/tree_T.gif",3,"","rengzheng/back/table/show.html","mainFrame",2,"打印汇款清单","","","../image/treeimg/tree_L.gif",3,"","rengzheng/back/print/show.html","mainFrame",1,0,"认证报告","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","#","_self",-1,2,"认证报告打印","","","../image/treeimg/tree_T.gif",3,"","rengzheng/print/show.html","mainFrame",2,"信封寄送","","","../image/treeimg/tree_L.gif",3,"","rengzheng/print/show1.html","mainFrame",1,0,"费用统计","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","#","_self",-1,2,"个人缴费查询","","","../image/treeimg/tree_T.gif",3,"","rengzheng/pay/individual.html","mainFrame",2,"集体付费查询","","","../image/treeimg/tree_L.gif",3,"","rengzheng/pay/group.html","mainFrame",1,1,5);
document.write('<style>');
document.write('TD.Tree_FOLDER_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('</style>');
var tree=new Tree_treeView();
tree.useImage=true;
tree.useTitleAsHint=true;
tree.useTitleAsStatus=true;
tree.useHint=true;
tree.useStatus=true;
tree.showSelect=true;
tree.showLine=false;
tree.Indent=13;
tree.folderImg1="";
tree.lineFolder="./";
tree.folderImg2="";
tree.fileImg="";
tree.target="_blank";
tree.folderClass1="Tree_FOLDER_1";
tree.folderClass2="Tree_FOLDER_2";
tree.folderClass3="Tree_FOLDER_3";
tree.fileClass1="Tree_FILE_1";
tree.fileClass2="Tree_FILE_2";
tree.fileClass3="Tree_FILE_3";
Tree_buildTree(tree_node,tree);
