var tree_node=new Array(0,"系统管理","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","#","_self",-1,2,"机构管理","","","../image/treeimg/tree_L.gif",3,"","system/department/show.html","mainFrame",0,"用户管理","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","#","_self",-1,2,"角色管理","","","../image/treeimg/tree_T.gif",3,"","system/user/row/show.html","mainFrame",2,"人员管理","","","../image/treeimg/tree_L.gif",3,"","system/user/user/show.html","mainFrame",1,0,"模板管理","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","#","_self",-1,2,"认证报告模板","","","../image/treeimg/tree_T.gif",3,"","system/model/report/show.html","mainFrame",2,"信封模板管理","","","../image/treeimg/tree_L.gif",3,"","system/model/envelope/show.html","mainFrame",1,2,"系统日志管理","","","../image/treeimg/tree_L.gif",3,"","system/data/show.html","mainFrame",1,5);
document.write('<style>');
document.write('TD.Tree_FOLDER_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('</style>');
var tree=new Tree_treeView();
tree.useImage=true;
tree.useTitleAsHint=true;
tree.useTitleAsStatus=true;
tree.useHint=true;
tree.useStatus=true;
tree.showSelect=true;
tree.showLine=false;
tree.Indent=13;
tree.folderImg1="";
tree.lineFolder="./";
tree.folderImg2="";
tree.fileImg="";
tree.target="_blank";
tree.folderClass1="Tree_FOLDER_1";
tree.folderClass2="Tree_FOLDER_2";
tree.folderClass3="Tree_FOLDER_3";
tree.fileClass1="Tree_FILE_1";
tree.fileClass2="Tree_FILE_2";
tree.fileClass3="Tree_FILE_3";
Tree_buildTree(tree_node,tree);
