var tree_node=new Array(0,"信息维护","","","../image/treeimg/clsfld.gif","../image/treeimg/openfld.gif",3,"","#","_self",-1,2,"学校信息","","","../image/treeimg/tree_T.gif",3,"","information/school/show.html","mainFrame",2,"使馆信息","","","../image/treeimg/tree_T.gif",3,"","information/embassy/show.html","mainFrame",2,"认证项目","","","../image/treeimg/tree_T.gif",3,"","information/project/show.html","mainFrame",2,"信封类型","","","../image/treeimg/tree_T.gif",3,"","information/envelope/show.html","mainFrame",2,"加急服务","","","../image/treeimg/tree_T.gif",3,"","information/rapid/show.html","mainFrame",2,"集体费用","","","../image/treeimg/tree_T.gif",3,"","information/group/show.html","mainFrame",2,"其他费用","","","../image/treeimg/tree_L.gif",3,"","information/other/show.html","mainFrame",1,5);
document.write('<style>');
document.write('TD.Tree_FOLDER_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('</style>');
var tree=new Tree_treeView();
tree.useImage=true;
tree.useTitleAsHint=true;
tree.useTitleAsStatus=true;
tree.useHint=true;
tree.useStatus=true;
tree.showSelect=true;
tree.showLine=false;
tree.Indent=13;
tree.folderImg1="";
tree.lineFolder="./";
tree.folderImg2="";
tree.fileImg="";
tree.target="_blank";
tree.folderClass1="Tree_FOLDER_1";
tree.folderClass2="Tree_FOLDER_2";
tree.folderClass3="Tree_FOLDER_3";
tree.fileClass1="Tree_FILE_1";
tree.fileClass2="Tree_FILE_2";
tree.fileClass3="Tree_FILE_3";
Tree_buildTree(tree_node,tree);
